//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Son_Kısım
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbsinavogrenciEntities : DbContext
    {
        public dbsinavogrenciEntities()
            : base("name=dbsinavogrenciEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dersler> dersler { get; set; }
        public virtual DbSet<tbl_notlar> tbl_notlar { get; set; }
        public virtual DbSet<tblkulupler> tblkulupler { get; set; }
        public virtual DbSet<tblogrenci> tblogrenci { get; set; }
    
        public virtual ObjectResult<kulupler_Result> kulupler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<kulupler_Result>("kulupler");
        }
    }
}
